# Generated by Django 5.2.6 on 2026-01-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=10)),
                ('image_data', models.TextField()),
            ],
        ),
    ]
