# Generated by Django 5.2.6 on 2025-10-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Auteur Inconnu', max_length=200),
            preserve_default=False,
        ),
    ]
