# Generated by Django 5.2.6 on 2026-01-01 19:49

import bonnes_lectures.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0002_remove_book_author_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=bonnes_lectures.fields.IsbnField(max_length=17, unique=True),
        ),
    ]
